setup(name='snake_pit',
      version='0.1',
      description='Customizable multi-processing system.',
      url='https://github.com/SalvatoreTosti/snake_pit',
      author='Salvatore Tosti',
      author_email='',
      license='MIT',
      packages=['snake_pit'],
      zip_safe=False)